services:
  spring-boot-service:
    container_name: spring-boot-service
    build: ./spring-boot-service
    depends_on:
      - postgres
    expose:
      - "8080"            
    networks:
      - plant-my-study

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"            
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - spring-boot-service
    networks:
      - plant-my-study
  
  postgres:
    container_name: postgres
    image: postgres:14.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - plant-my-study

networks:
  plant-my-study:
    driver: bridge
