services:
  spring-boot-service:
    container_name: spring-boot-service
    build: ./spring-boot-service
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - JWT_SECRET_FILE=/run/secrets/spring-boot-jwt-secret
    secrets:
      - spring-boot-jwt-secret
    ports:
      - "8080:8080"
    networks:
      - plant-my-study
    volumes:
      - ./spring-boot-service:/app

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"            
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - spring-boot-service
    networks:
      - plant-my-study
  
  postgres:
    container_name: postgres
    image: postgres:14.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./pg-dump:/docker-entrypoint-initdb.d
    networks:
      - plant-my-study

networks:
  plant-my-study:
    driver: bridge

secrets:
  spring-boot-jwt-secret:
    file: ./secrets/spring-boot-jwt
