services:
  spring-boot-service:
    container_name: spring-boot-service
    build: ./spring-boot-service
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - JWT_SECRET_FILE=/run/secrets/spring-boot-jwt-secret
    secrets:
      - spring-boot-jwt-secret
    ports:
      - "8080:8080"
    networks:
      - plant-my-study
    volumes:
      - ./spring-boot-service:/app
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/test"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # ! jasiu dodaj jakis healthcheck zeby mozna bylo pingowac co jakis czas bo to sie przyda nam pls
    # ! a test nie dziala bo potrzebuje to chyba tego tokenu co nie

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"            
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - spring-boot-service
    # depends_on:
    #   spring-boot-service:
    #     condition: service_healthy
    # ! to zmienic jak bedzie dobry healthcheck
    networks:
      - plant-my-study
    restart: on-failure
  
  postgres:
    container_name: postgres
    image: postgres:14.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./pg-dump:/docker-entrypoint-initdb.d
    networks:
      - plant-my-study

networks:
  plant-my-study:
    driver: bridge

secrets:
  spring-boot-jwt-secret:
    file: ./secrets/spring-boot-jwt
